import os
import sh
import sys
import argparse
from os import path


def __concat_dts(dts_paths, out_dts_path):
    out_path = path.dirname(out_dts_path)
    if not path.exists(out_path):
        os.makedirs(out_path)

    with open(out_dts_path, "w") as wfd:
        wfd.write(f"// Generated by devicetree_gen.py \n\n")

        for dts_path in dts_paths:
            with open(dts_path, "r") as fd:
                wfd.write(f"\n\n")
                wfd.write(f"// {dts_path} \n\n")
                wfd.writelines(fd.readlines())


def __compile_dts(dts_path, out_dtb_path, verbose):
    out_path = path.dirname(out_dtb_path)
    if not path.exists(out_path):
        os.makedirs(out_path)

    out = None
    err = None
    if verbose:
        out = sys.stdout
        err = sys.stderr

    sh.dtc("-I", "dts", "-O", "dtb", "-o", out_dtb_path, dts_path, _out=out, _err=err)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("--out-dts", type=str, required=True)
    parser.add_argument("--out-dtb", type=str, required=True)
    parser.add_argument("dts", type=str, nargs="+")

    args = parser.parse_args()

    __concat_dts(args.dts, args.out_dts)
    __compile_dts(args.out_dts, args.out_dtb, args.verbose)
