import os
import argparse
from os import path


def __concat_src_files(out_c_path, src_paths):
    out_path = path.dirname(out_c_path)
    if not path.exists(out_path):
        os.makedirs(out_path)

    with open(out_c_path, "w") as wfd:
        wfd.write(f"// Generated by kernel_src_gen.py \n\n")

        for src_path in src_paths:
            with open(src_path, "r") as fd:
                wfd.write(f"\n\n")
                wfd.write(f'#line 1 "{src_path}" \n\n')
                wfd.writelines(fd.readlines())


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=str, required=True)
    parser.add_argument("srcs", nargs="+")

    args = parser.parse_args()

    __concat_src_files(args.out, args.srcs)
